pipeline {
    agent any
    stages {
        stage('Barcelona') {
            steps {
                script {
                    echo 'La ciudad de Barcelona tiene una población de 80000.0'
                }
            }
        }
        stage('Madrid') {
            steps {
                script {
                    echo 'La ciudad de Madrid tiene una población de 800000.0'
                }
            }
        }
         stage('Málaga') {
            steps {
                script {
                    echo 'La ciudad de Malaga (la mejor de todas) tiene una población de 40000.0'
                }
            }
        }
		stage('Sevilla') {
            steps {
                script {
                    echo 'La ciudad de Sevilla tiene una población de 64000.0'
                }
            }
        }
    }
}